const ShopActionType = {
  GET_COLLECTION_BY_ID: "GET_COLLECTION_BY_ID",
  UPDATE_COLLECTIONS: "UPDATE_COLLECTIONS",
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE"
};
export default ShopActionType;
