export const cartActionType = {
  HIDE_CART_DROPDOWN: "HIDE_CART_DROPDOWN",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_TO_CART: "REMOVE_TO_CART",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  CART_CLEAR: "CART_CLEAR"
};
